document.write('<nav>');
document.write('<ul>');
document.write('<li><a href="index.html">ホーム</a></li>');
document.write('<li><a href="about.html">stsicについて</a></li>');
document.write('<li><a href="music-study.html">勉強中の音楽っていいの？</a></li>');
document.write('<li><a href="random.html">ランダム表示</a></li>');
document.write('</ul>');
document.write('<ul>');
document.write('<li><a href="./category/jazz/">ジャズ(カフェ)</a></li>');
document.write('<li><a href="./category/j-pop/">j-pop</a></li>');
document.write('<li><a href="./category/western-music/">洋楽</a></li>');
document.write('<li><a href="./category/edm/">EDM</a></li>');
document.write('<li><a href="./category/japanese-style/">和風</a></li>');
document.write('<li><a href="./category/ghibli/">ジブリ</a></li>');
document.write('<li><a href="./category/disney/">ディズニー</a></li>');
document.write('<li><a href="./category/music-box/">オルゴール</a></li>');
document.write('<li><a href="./category/piano/">ピアノ</a></li>');
document.write('<li><a href="./category/natural-sound/">自然音</a></li>');
document.write('<li><a href="./category/study-sound/">勉強中の音</a></li>');
document.write('<li><a href="./category/animal-crossing/">あつ森</a></li>');
document.write('<li><a href="./category/alpha-wave/">α波</a></li>');
document.write('<li><a href="./category/classic/">クラシック</a></li>');
document.write('<li><a href="./category/celtic-music/">ケルト音楽</a></li>');
document.write('<li><a href="./category/vocaloid/">ボカロ</a></li>');
document.write('</ul>');
document.write('<ul>');
document.write('<li><a href="notice.html">お知らせ</a></li>');
document.write('<li><a href="report-bugs.html">バグの報告</a></li>');
document.write('<li><a href="add-to-content.html">コンテンツ追加要望</a></li>');
document.write('<li><a href="contact.html">お問い合わせ</a></li>');
document.write('<li><a href="privacy-policy.html">プライバシーポリシー</a></li>');
document.write('</ul>');
document.write('</nav>');
//広告
document.write('<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>');
//サイドバー最下
document.write('<ins class="adsbygoogle"');
document.write('style="display:block"');
document.write('data-ad-client="ca-pub-3868968729859777"');
document.write('data-ad-slot="3893022053"');
document.write('data-ad-format="auto"');
document.write('data-full-width-responsive="true"></ins>');
document.write('<script>');
document.write(' (adsbygoogle = window.adsbygoogle || []).push({});');
document.write('</script>');
